name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: '*/5 * * * *'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          process-only: 'pr'
          pr-comment: 'Unfortunately, we do not accept pull requests on GitHub.'