name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          process-only: 'pr'
          pr-comment: 'This repository does not accept pull requests on Github, see the README.md for details.'